apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-clean-controller
  labels:
    app: job-clean
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-clean
  template:
    metadata:
      labels:
        app: job-clean
    spec:
      containers:
      - name: job-clean
        image: wwyizhang/caksu:latest
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
