apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-cleaner-controller
  labels:
    app: job-cleaner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: job-cleaner
    spec:
      containers:
      - name: job-cleaner
        image: wwyizhang/job-cleaner:latest
