apiVersion: batch/v1
kind: Job
metadata: 
  name: test-job2
spec:
  template:
    spec:
      containers:
      - name: run-busybox
        image: library/busybox:latest
        command: ["/bin/bash", "-c", "sleep 3600"]
      restartPolicy: Never
  backoffLimit: 3